version: '3.9'
services:

  webapp-core:
    build: .
    volumes:
      - ./:/webapp-core
    env_file: .env
    ports:
      - "8080:8080"
    # command: [ "sh", "-c", "./bin/api" ]
    # command: [ "sh", "-c", "go run cmd/api/main.go" ]
    command: [ "sh", "-c", "CompileDaemon --build='go build ./cmd/api/main.go' --command=./main"]
    restart: always
  
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=app_pass
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app_user -d app_db" ]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always
